# Site settings
name: Damilare Emmanuel O.
title: Oyelakin Damilare Emmanuel | Full Stack Software Engineer
description: Software engineer focused on developing softwares to increase productivity &amp; improved user experiences.
url: https://damilareemmanuel.com/
baseurl: ""
email: d.dammylarry@gmail.com
cover: https://damilareemmanuel.com/img/og.png
logo: https://damilareemmanuel.com/img/emojis/technologist.png
resume: https://damilareemmanuel.com/resume.pdf
social:
  - title: email
    url: mailto:d.dammylarry@gmail.com
  - title: twitter
    url: https://twitter.com/echo_dammy
  - title: medium
    url: https://medium.com/@d.dammylarry
  - title: stackoverflow
    url: https://stackoverflow.com/users/7593083/netemmanuel
  - title: github
    url: https://github.com/netEmmanuel
  - title: linkedin
    url: https://www.linkedin.com/in/damilare-emmanuel-aa965094/
# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
